spring:
  datasource:
    url: jdbc:sqlserver://localhost;selectMethod=direct;sendStringParametersAsUnicode=false
    username: SA
    password: "Your_password123"

example:
  use-shared-incrementer: false
  create-database: true
  stress-test-thread-count: 4
  samples-per-thread: 100
    

